"""Morning report generator — summarises overnight agent work."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path


def _load_tasks(bucket_dir: Path) -> list[dict]:
    tasks = []
    if not bucket_dir.exists():
        return tasks
    for f in sorted(bucket_dir.glob("*.json")):
        try:
            tasks.append(json.loads(f.read_text()))
        except json.JSONDecodeError:
            pass
    return tasks


def generate_report(project_root: Path, since: datetime | None = None) -> str:
    """Generate a markdown morning report of overnight work.

    Args:
        project_root: Project root directory.
        since: Only include tasks completed/failed after this time. None = all.

    Returns:
        Markdown string.
    """
    wf = project_root / ".workflow"
    completed = _load_tasks(wf / "tasks" / "completed")
    failed = _load_tasks(wf / "tasks" / "failed")
    pending = _load_tasks(wf / "tasks" / "pending")

    if since:

        def _after(task: dict, key: str) -> bool:
            ts = task.get(key)
            if not ts:
                return False
            try:
                return datetime.fromisoformat(ts) >= since
            except ValueError:
                return False

        completed = [t for t in completed if _after(t, "completed_at")]
        failed = [t for t in failed if _after(t, "failed_at")]

    now = datetime.now()
    lines = [
        "# Overnight Agent Report",
        "",
        f"**Date:** {now.strftime('%Y-%m-%d')}  ",
        f"**Generated:** {now.strftime('%H:%M:%S')}",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Status | Count |",
        "|---|---|",
        f"| ✅ Completed | {len(completed)} |",
        f"| ❌ Failed | {len(failed)} |",
        f"| ⏭️ Still pending | {len(pending)} |",
        f"| **Total** | **{len(completed) + len(failed) + len(pending)}** |",
        "",
    ]

    if completed:
        lines += ["## ✅ Completed Tasks", ""]
        for task in completed:
            commit = task.get("commit_hash", "no-commit")[:8]
            ts = (task.get("completed_at") or "")[:19]
            lines.append(f"- **{task['id']}** — {task.get('description', '')}  ")
            lines.append(f"  `{commit}` at {ts}")
        lines.append("")

    if failed:
        lines += ["## ❌ Failed Tasks", ""]
        for task in failed:
            ts = (task.get("failed_at") or "")[:19]
            error = task.get("last_error", "unknown error")
            lines.append(f"- **{task['id']}** — {task.get('description', '')}  ")
            lines.append(f"  Error at {ts}: {error}")
        lines.append("")

    if pending:
        lines += ["## ⏭️ Still Pending", ""]
        for task in pending:
            lines.append(f"- **{task['id']}** — {task.get('description', '')}")
        lines.append("")

    lines += ["---", "", "*Generated by workflow-kit*"]
    return "\n".join(lines)


def save_report(project_root: Path, content: str) -> Path:
    """Save report to .workflow/reports/YYYY-MM-DD-overnight.md."""
    reports_dir = project_root / ".workflow" / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")
    path = reports_dir / f"{date_str}-overnight.md"
    path.write_text(content)
    return path
